### ISSUE TITLE
Docker error "you have reach your pull rate limit" during CI

### ISSUE THREAD

**Issue by elombardi2** [smartgov-liris/SmartGov-docker#2]
Some CI builds fail with the error "you have reach your pull rate limit" due to Docker limiting the number of pull from Travis service.
See [here](https://blog.addressfinder.io/quick-fix-for-dockers-toomanyrequests-you-have-reached-your-pull-rate-limit-from-travis-64410327e8e6) for a complete explanation of the issue and a solution.
The solution is to create a Docker account, then to link the CI with this account.

**Comment by vdeslandres** [comment]
I've created a Docker Hub account, but I don't know how to link it with our Travis CI. I've added your 2 email addresses within the Docker account, perhaps it allows you to perform the link with the CI.

**Comment by vdeslandres** [comment]
The environment variable corresponding to the new DockerID was added in Travis and the script of the build has been changed with the new Docker account.

**Comment by elombardi2** [comment]
Build script changed by [this commit](https://github.com/smartgov-liris/SmartGov-docker/commit/4c7e2406523677fb664ed0a189a65dc5255de1c6).
